# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re
from selenium.webdriver.support.ui import WebDriverWait 

class Ops05Testcase(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.base_url = "http://ops05.edaixi.cn:81"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_ops05_testcase(self):
        driver = self.driver
        driver.get(self.base_url + "/")
        driver.find_element_by_link_text(u"登陆").click()
        print driver.title,"UI Testing starting ......"
        driver.implicitly_wait(20)
        driver.find_element_by_id("username").clear()
        driver.find_element_by_id("username").send_keys("test")
        driver.find_element_by_id("password").clear()
        driver.find_element_by_id("password").send_keys("test")
        driver.find_element_by_id("login-submit").click()
        WebDriverWait(driver, 10).until(lambda the_driver: the_driver.find_element_by_link_text(u"权限管理").is_displayed()) 
        driver.find_element_by_link_text(u"权限管理").click()
        #driver.find_element_by_css_selector("ul.dropdown-menu > li > a").click()
        #driver.find_element_by_link_text(u"权限管理").click()
        driver.find_element_by_link_text(u"岗位管理").click()
        driver.find_element_by_link_text(u"新建").click()
        Select(driver.find_element_by_id("position_to_role_position")).select_by_visible_text(u"市场策划")
        Select(driver.find_element_by_id("position_to_role_role_key")).select_by_visible_text(u"市场经理")
        driver.find_element_by_name("commit").click()
        driver.find_element_by_xpath(u"(//a[contains(text(),'编辑')])[6]").click()
        Select(driver.find_element_by_id("position_to_role_role_key")).select_by_visible_text(u"城市经理")
        driver.find_element_by_name("commit").click()
        time.sleep(2)
        driver.find_element_by_xpath(u"(//a[contains(text(),'删除')])[6]").click()
        self.assertRegexpMatches(self.close_alert_and_get_its_text(), u"^确认删除岗位角色映射[\s\S]$")
        time.sleep(2)
        #driver.back()
        driver.find_element_by_link_text(u"版面管理").click()
        driver.find_element_by_link_text(u"顶部banner图片").click()
        #driver.find_element_by_link_text(u"选择").click()
        #self.assertRegexpMatches(self.close_alert_and_get_its_text(), u"^确认选择[\s\S]$")
        driver.find_element_by_link_text(u"上移").click()
        self.assertRegexpMatches(self.close_alert_and_get_its_text(), u"^确认上移[\s\S]$")
        time.sleep(1)
        driver.find_element_by_link_text(u"下移").click()
        self.assertRegexpMatches(self.close_alert_and_get_its_text(), u"^确认下移[\s\S]$")
        time.sleep(1)
        driver.back()
        driver.find_element_by_link_text(u"版面管理").click()
        driver.find_element_by_link_text(u"大功能按钮管理").click()
        driver.back()
        time.sleep(2)
        driver.find_element_by_link_text(u"版面管理").click()
        driver.find_element_by_link_text(u"小功能按钮管理").click()
        driver.back()
        #driver.find_element_by_link_text(u"分销系统").click()
        time.sleep(2)
        driver.find_element_by_link_text(u"分销系统").click()
        driver.find_element_by_id("product_name").clear()
        driver.find_element_by_id("product_name").send_keys(u"测试")
        driver.find_element_by_name("commit").click()
        driver.find_element_by_link_text(u"类目管理").click()
        driver.find_element_by_link_text(u"类目上线申请").click()
        driver.find_element_by_link_text(u"查看详细").click()
        driver.find_element_by_link_text(u"新 建").click()
        driver.find_element_by_id("service_good_form_name").clear()
        driver.find_element_by_id("service_good_form_name").send_keys("xipijian")
        driver.find_element_by_id("service_good_form_price").clear()
        driver.find_element_by_id("service_good_form_price").send_keys("199")
        driver.find_element_by_id("service_good_form_unit_name").clear()
        driver.find_element_by_id("service_good_form_unit_name").send_keys("edaixi")
        driver.find_element_by_id("service_good_form_description").clear()
        driver.find_element_by_id("service_good_form_description").send_keys("xiaxia")
        driver.find_element_by_name("commit").click()
        time.sleep(2)
        driver.find_element_by_xpath(u"(//a[contains(text(),'编辑')])[11]").click()
        driver.find_element_by_id("service_good_form_description").clear()
        driver.find_element_by_id("service_good_form_description").send_keys("xiaxia111")
        driver.find_element_by_name("commit").click()
        time.sleep(2)
        driver.find_element_by_xpath(u"(//a[contains(text(),'取消申请')])[4]").click()
        self.assertRegexpMatches(self.close_alert_and_get_its_text(), u"^确认取消申请[\s\S]$")
        time.sleep(2)
        driver.find_element_by_link_text(u"使用模板新建").click()
        driver.find_element_by_id("service_good_form_description").clear()
        driver.find_element_by_id("service_good_form_description").send_keys("111")
        driver.find_element_by_name("commit").click()
        time.sleep(1)
        driver.back()
        driver.find_element_by_link_text(u"价格体系管理").click()
        driver.find_element_by_link_text(u"洗鞋").click()
        driver.back()
        driver.find_element_by_link_text(u"运费管理").click()
        driver.find_element_by_link_text(u"运费设置").click()
        driver.find_element_by_link_text(u"新增运费阶梯").click()
        driver.find_element_by_id("delivery_fee_setting_form_sentinel_min").clear()
        driver.find_element_by_id("delivery_fee_setting_form_sentinel_min").send_keys("11")
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").clear()
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").send_keys("12")
        driver.find_element_by_name("commit").click()
        time.sleep(1)
        driver.find_element_by_id("delivery_fee_setting_form_sentinel_min").clear()
        driver.find_element_by_id("delivery_fee_setting_form_sentinel_min").send_keys("15")
        driver.find_element_by_name("commit").click()
        time.sleep(1)
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").clear()
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").send_keys("1")
        driver.find_element_by_name("commit").click()
        time.sleep(1)
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").clear()
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").send_keys("4")
        driver.find_element_by_name("commit").click()
        driver.back()
        driver.find_element_by_link_text(u"运费管理").click()
        driver.find_element_by_link_text(u"运费设置").click()
        driver.find_element_by_link_text(u"新增运费阶梯").click()
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").clear()
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").send_keys("22")
        driver.find_element_by_id("delivery_fee_setting_form_sentinel_min").clear()
        driver.find_element_by_id("delivery_fee_setting_form_sentinel_min").send_keys("22")
        driver.find_element_by_name("commit").click()
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").clear()
        driver.find_element_by_id("delivery_fee_setting_form_delivery_fee").send_keys("12")
        driver.find_element_by_name("commit").click()
        #driver.find_element_by_name("commit").click()
        driver.back()
        driver.find_element_by_link_text(u"运费管理").click()
        driver.find_element_by_link_text(u"下单提示管理").click()
        driver.find_element_by_link_text(u"新 建").click()
        driver.find_element_by_id("order_tip_content").clear()
        driver.find_element_by_id("order_tip_content").send_keys("111")
        driver.find_element_by_id("order_tip_start_time").click()
        driver.find_element_by_link_text("22").click()
        driver.find_element_by_id("order_tip_end_time").click()
        driver.find_element_by_link_text("23").click()
        driver.find_element_by_name("commit").click()
        time.sleep(2)
        driver.find_element_by_xpath(u"(//a[contains(text(),'编辑')])[4]").click()
        driver.find_element_by_id("order_tip_content").clear()
        driver.find_element_by_id("order_tip_content").send_keys("111222")
        driver.find_element_by_name("commit").click()
        time.sleep(2)
        driver.find_element_by_xpath(u"(//a[contains(text(),'取消申请')])[3]").click()
        self.assertRegexpMatches(self.close_alert_and_get_its_text(), u"^确认取消申请[\s\S]$")
        #driver.back()
        time.sleep(2)
        driver.find_element_by_link_text(u"衣物管理").click()
        driver.find_element_by_link_text(u"瑕疵管理").click()
        time.sleep(1)
        driver.find_element_by_link_text(u"洗鞋").click()
        time.sleep(1)
        driver.find_element_by_link_text(u"家纺").click()
        
        time.sleep(1)
        #driver.back()
        
        driver.find_element_by_link_text(u"衣物管理").click()
        driver.find_element_by_link_text(u"后端价格管理").click()
        
        time.sleep(1)
        #driver.back()
        driver.find_element_by_link_text(u"衣物管理").click()
        driver.find_element_by_link_text(u"品牌管理").click()
        
        time.sleep(1)
        #driver.back()
        driver.find_element_by_link_text(u"衣物管理").click()
        driver.find_element_by_link_text(u"效果管理").click()
        time.sleep(1)
        driver.find_element_by_link_text(u"洗鞋").click()
        time.sleep(1)
        driver.find_element_by_link_text(u"家纺").click()
        time.sleep(2)
        driver.back()
        driver.find_element_by_link_text(u"限单管理").click()
        time.sleep(1)
        driver.find_element_by_link_text(u"洗鞋").click()
        time.sleep(1)
        driver.find_element_by_link_text(u"模板下载").click()
        time.sleep(1)
        driver.switch_to_alert()
        WebDriverWait(driver, 10).until(lambda the_driver: the_driver.switch_to_alert().text()) 
        driver.back()
        driver.find_element_by_link_text(u"模板上传").click()
        time.sleep(1)
        driver.back()
        driver.find_element_by_link_text(u"限单管理").click()
        print driver.title,"UI Testing has been completed."
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException, e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException, e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
